name: Deploy to s3
on:
  push:
    branches:
      - staging
jobs:
  build:
    name: Build files
    runs-on: ubuntu-latest
    steps: 
    - name: Setup node
      uses: actions/setup-node@v1
      with: 
          node-version: '16.x'
    - uses: actions/checkout@master
    - name: Deploy to s3
      env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
      run: |
        aws s3 sync legislativeaffairs "s3://staging-phila-gov-website-s3/departments/mayor/legislative-affairs-documents/"
        aws s3 sync legislativeaffairs_json "s3://staging-phila-gov-website-s3/departments/mayor/legislative-affairs-json/" --delete
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_INVALIDATE_PROD }} --paths "/*"
